---
- hosts: all
  vars:
    COLOUR_SCIENCE__ROOT_DIRECTORY: "{{ lookup('env','COLOUR_SCIENCE__ROOT_DIRECTORY') or '/colour-science' }}"
    COLOUR_SCIENCE__PYTHON_VERSION: "{{ lookup('env','COLOUR_SCIENCE__PYTHON_VERSION') or '3.10' }}"
    COLOUR_SCIENCE__ACTIVE_PROJECTS: "{{ lookup('env','COLOUR_SCIENCE__ACTIVE_PROJECTS') or 'awesome-colour:colour:colour-demosaicing:colour-hdri:colour-checker-detection:colour-datasets:colour-visuals:colour-dash:colour-science.org:colour-branding:colour-mitsuba:colour-nuke:colour-webhook' }}"
    COLOUR_SCIENCE__JUPYTER_NOTEBOOK_PORT: "{{ lookup('env','COLOUR_SCIENCE__JUPYTER_NOTEBOOK_PORT') or '8888' }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  tasks:
    - import_tasks: "tasks/install_apt_dependencies.yml"
    - import_tasks: "tasks/install_uv.yml"

    # Project: Awesome Colour
    - import_tasks: "tasks/install_project.yml"
      when: "'awesome-colour' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: awesome-colour

    # Project: Colour
    - import_tasks: "tasks/install_project.yml"
      when: "'colour' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour

    # Project: Colour - Demosaicing
    - import_tasks: "tasks/install_project.yml"
      when: "'colour-demosaicing' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour-demosaicing

    # Project: Colour - HDRI
    - import_tasks: "tasks/install_project.yml"
      when: "'colour-hdri' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour-hdri

    # Project: Colour - Checker Detection
    - import_tasks: "tasks/install_project.yml"
      when: "'colour-checker-detection' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour-checker-detection

    # Project: Colour - Datasets
    - import_tasks: "tasks/install_project.yml"
      when: "'colour-datasets' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour-datasets

    # Project: Colour - Visuals
    - import_tasks: "tasks/install_project.yml"
      when: "'colour-visuals' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour-visuals

    # Project: Colour - Dash
    - import_tasks: "tasks/install_project.yml"
      when: "'colour-dash' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour-dash

    # Project: colour-science.org
    - import_tasks: "tasks/install_project.yml"
      when: "'colour-science.org' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        project: colour-science.org

    # Repository: Colour - Branding
    - import_tasks: "tasks/clone_repository.yml"
      when: "'colour-branding' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        repository: colour-branding

    # Repository: Colour - Mitsuba
    - import_tasks: "tasks/clone_repository.yml"
      when: "'colour-mitsuba' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        repository: colour-mitsuba

    # Repository: Colour - Nuke
    - import_tasks: "tasks/clone_repository.yml"
      when: "'colour-nuke' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        repository: colour-nuke

    # Repository: Colour - Webhook
    - import_tasks: "tasks/clone_repository.yml"
      when: "'colour-webhook' in COLOUR_SCIENCE__ACTIVE_PROJECTS"
      vars:
        repository: colour-webhook
